name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency: ci-addr-docker-${{ github.ref_name }}

    env:
      ORG_GRADLE_PROJECT_onstructiveUsername: ${{ secrets.M2_USER }}
      ORG_GRADLE_PROJECT_onstructivePassword: ${{ secrets.M2_PWD }}
      M2_USER: ${{ secrets.M2_USER}}
      M2_PWD: ${{ secrets.M2_PWD }}

    services:
      smocker:
        image: thiht/smocker:0.18.2
        ports:
          - 8080:8080
          - 8081:8081

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: -s check publishToMavenLocal

    - name: Publish JARs
      uses: gradle/gradle-build-action@v2
      with:
        arguments: -s artifactoryPublish

